name: build

on: [push]

jobs:
    test_script:
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.x"
                architecture: "x64"
            
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip3 install --requirement requirements.txt

          - name: Test the script
            run: |
                python main.py -h

    # build_image:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Checkout
    #         uses: actions/checkout@v3
