name: build

on: [push]

jobs:
    test_script:
        reads-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.x"
            
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --quiet --requirement requirements.txt

            - name: Test the script
              uses: |
                  python main.py -h