name: build

on: [push]

env:
  SCRIPT_HELP: script_help
  DOCKER_HELP: docker_help

jobs:
    test_script:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.10" # Python> 3.10 cause error in installing h5py & pyarrow
            
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install --quiet --requirement requirements.txt

          - name: Test the script
            run: |
                python main.py -h > log_script.txt

          - name: Upload the artifact
            uses: actions/upload-artifact@v3.1.2
            with:
                name: ${{ env.SCRIPT_HELP }}
                path: ./log.txt

    build_test_image:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Build and tag image
            run: |
                docker build -t exp_env:0.0.1 .
          - name: Test image
            run: |
                docker run --rm -it exp_env:0.0.1 main.py -h > log_docker.txt
