name: Build and push main image

on:
  push:
    branches:
    - master
    - main

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'set .env file'
        env:
          ENV_VALUE: ${{ secrets.ENV }}
        run: |
          echo ${ENV_VALUE} | base64 -d >> .env

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/${REPO}:${GITHUB_REF##*/}
          docker push ghcr.io/${REPO}:${GITHUB_REF##*/}
